# Generated by Django 5.0 on 2023-12-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=45)),
                ('modele', models.CharField(max_length=45)),
                ('annee', models.IntegerField()),
                ('cylindree', models.IntegerField()),
                ('version', models.CharField(max_length=45)),
            ],
        ),
    ]
