# Generated by Django 5.0 on 2023-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='annee',
            field=models.IntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylindree',
            field=models.IntegerField(verbose_name='Cylindrée en cm3'),
        ),
    ]
