# Generated by Django 5.0 on 2023-12-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='note',
            field=models.IntegerField(default='Non notée', max_length=2),
        ),
    ]
