# Generated by Django 5.0 on 2023-12-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='note',
            field=models.IntegerField(),
        ),
    ]
