# Generated by Django 5.0 on 2023-12-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='notation',
            field=models.IntegerField(null=True),
        ),
    ]
